Repository synfig/synfig, pull requests merged in 2020-07, with the labels that each got.

#1561 Don't crash if exception thrown while rendering WorkArea
  synfig-core/src/synfig/exception.cpp
  synfig-core/src/synfig/exception.h
  synfig-studio/src/gui/exception_guard.h
  synfig-studio/src/gui/workarea.cpp
  synfig-studio/src/synfigapp/value_desc.cpp
  synfig-studio/src/synfigapp/value_desc.h
Labels: Crash

#1564 fix crash when user deletes the sound layer being shown in Sound panel
  synfig-studio/src/gui/docks/dock_soundwave.cpp
Labels: Crash

#1551 fix crash when undoing creation of a moved/changed vertex of spline
  synfig-studio/src/gui/trees/historytreestore.cpp
  synfig-studio/src/gui/trees/historytreestore.h
Labels: Crash

#1432 Fix text layer family search and allow user selection
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-studio/configure.ac
  synfig-studio/po/POTFILES.in
  synfig-studio/src/gui/widgets/CMakeLists.txt
  synfig-studio/src/gui/widgets/Makefile_insert
  synfig-studio/src/gui/widgets/widget_fontfamily.cpp
  synfig-studio/src/gui/widgets/widget_fontfamily.h
  synfig-studio/src/gui/widgets/widget_value.cpp
  synfig-studio/src/gui/widgets/widget_value.h
Labels: Text

#1491 Changes for appveyor build using CMake and ninja.
  1-setup-windows-msys2.sh
  2-build-msys-cmake.sh
  CMakeLists.txt
  appveyor.yml
  autobuild/msys2/appveyor.bat
  autobuild/msys2/build_mlt.sh
  cmake/InstallMSYS2.cmake
  cmake/SynfigGettext.cmake
  cmake/SynfigIntltool.cmake
  synfig-core/src/CMakeLists.txt
  synfig-studio/CMakeLists.txt
  synfig-studio/plugins/CMakeLists.txt
  synfig-studio/plugins/add-skeleton-simple/CMakeLists.txt
  synfig-studio/plugins/lottie-exporter/CMakeLists.txt
  synfig-studio/plugins/view-unhide-all-layers/CMakeLists.txt
Labels: CMake
