Repository synfig/synfig, pull requests merged in 2020-11, with the labels that each got.

#1828 fix regression: text layer accepts font filename again
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
Labels: Backport

#1829 fix Duplicate layer ignoring all layers but the first one
  synfig-core/src/synfig/context.cpp
  synfig-core/src/synfig/context.h
  synfig-core/src/synfig/layers/layer_duplicate.cpp
Labels: Backport

#1826 fix animation interpolation for boolean values
  synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp
Labels: Backport

#1830 Fixed error when output to MPEG-1 format with audio
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Labels: Backport

#1834 [MacOS] Fixed SynfigStudio.app won't start if renamed
  autobuild/osx/app-template/Contents/Info.plist
  autobuild/osx/synfig_osx_launcher.cpp
Labels: Backport, MacOS

#1819 [CMake] Added CFLAGS from MagickCore to mod_magickpp (fixes build in some OS)
  synfig-core/src/modules/mod_magickpp/CMakeLists.txt
  synfig-core/src/modules/mod_magickpp/config.h.cmake.in
Labels: CMake
