Repository synfig/synfig, pull requests merged in 2021-04, with the labels that each got.

#2096 [MSVC] Fixed unresolved external symbol error when building `lyr_std`
  synfig-core/src/modules/mod_particle/plant.cpp
  synfig-core/src/synfig/layer.cpp
  synfig-core/src/synfig/layer.h
  synfig-core/src/synfig/module.h
Labels: Windows

#2102 [Synfig Studio] Sometimes Widget_Vector didn't use locale for decimal separator
  synfig-core/src/synfig/string_helper.cpp
  synfig-core/src/synfig/string_helper.h
  synfig-studio/src/gui/widgets/widget_vector.cpp
Labels: Backport

#2097 [Synfig Studio] Seek to begin/end follow playback bounds set by user
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
Labels: UI/UX

#2092 [Synfig Studio] Exported canvas can be reopened after closing
  synfig-studio/src/gui/canvasview.cpp
Labels: Backport

#2109 [Synfig Studio] 'Undock Panel' menu item is no longer visible for already undocked panels
  synfig-studio/src/gui/docks/dockbook.cpp
Labels: Backport, GUI

#2120 [Synfig Studio] Fixed an issue due to which menus were not displayed on all panels except the canvas
  synfig-studio/src/gui/docks/dockbook.cpp
Labels: Backport

#2116 [Synfig Studio] Fixed crash when user drags a group to a child group
  synfig-studio/src/gui/trees/layertreestore.cpp
Labels: Backport, Crash

#2128 [CMake] Bump minimum required CMake version to 3.5
  CMakeLists.txt
  ETL/CMakeLists.txt
  synfig-core/CMakeLists.txt
  synfig-core/src/CMakeLists.txt
  synfig-studio/CMakeLists.txt
  synfig-studio/src/CMakeLists.txt
Labels: CMake

#2130 [CMake] Fixed splash screen creation when build type is differs from Debug/Release
  synfig-studio/images/CMakeLists.txt
Labels: CMake
