Repository synfig/synfig, pull requests merged in 2021-07, with the labels that each got.

#2187 Replaced deprecated Gtk::Alignment class using Widget margins
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/dialogs/canvasproperties.cpp
  synfig-studio/src/gui/dialogs/dialog_soundselect.cpp
  synfig-studio/src/gui/dialogs/vectorizersettings.cpp
  synfig-studio/src/gui/renddesc.cpp
  synfig-studio/src/gui/render.cpp
  synfig-studio/src/gui/widgets/widget_defaults.cpp
  synfig-studio/src/gui/widgets/widget_defaults.h
Labels: GSoC

#2206 Clean synfigapp::ValueDesc a bit
  synfig-studio/src/synfigapp/actions/valuedesclink.cpp
  synfig-studio/src/synfigapp/actions/valuedesclink.h
  synfig-studio/src/synfigapp/value_desc.h
Labels: Code quality

#2194 Removed excessive use of std namespace (part 2)
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-core/src/modules/lyr_std/bevel.cpp
  synfig-core/src/modules/lyr_std/booleancurve.cpp
  synfig-core/src/modules/mod_bmp/mptr_bmp.cpp
  synfig-core/src/modules/mod_filter/radialblur.cpp
  synfig-core/src/modules/mod_filter/radialblur.h
  synfig-core/src/modules/mod_geometry/rectangle.cpp
  synfig-core/src/modules/mod_gif/trgt_gif.cpp
  synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
  synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.cpp
  synfig-core/src/modules/mod_noise/noise.cpp
  synfig-core/src/modules/mod_yuv420p/trgt_yuv.cpp
  synfig-core/src/synfig/layers/layer_bitmap.cpp
  synfig-core/src/synfig/layers/layer_motionblur.cpp
  synfig-core/src/synfig/valuenodes/valuenode_add.cpp
  synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp
  synfig-core/src/synfig/valuenodes/valuenode_average.cpp
  synfig-core/src/synfig/valuenodes/valuenode_boneinfluence.cpp
  synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
  synfig-core/src/synfig/valuenodes/valuenode_dilist.cpp
  synfig-core/src/synfig/valuenodes/valuenode_integer.cpp
  synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.cpp
  synfig-studio/src/gui/states/state_bline.cpp
  synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
  synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
  synfig-studio/src/synfigapp/canvasinterface.cpp
  synfig-studio/src/synfigapp/settings.cpp
  synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp
Labels: Code quality

#2207 Added support for Rhubarb Lip Sync TSV and XML file formats for ValueNode_AnimatedFile
  synfig-core/src/synfig/canvasfilenaming.cpp
  synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
  synfig-core/src/synfig/valuenodes/valuenode_animatedfile.h
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
  synfig-studio/src/synfigapp/canvasinterface.cpp
Labels: Enhancement

#2199 [Lottie exporter] Add support for export of Advanced outline
  synfig-studio/plugins/lottie-exporter/CMakeLists.txt
  synfig-studio/plugins/lottie-exporter/common/Angle.py
  synfig-studio/plugins/lottie-exporter/common/DashItem.py
  synfig-studio/plugins/lottie-exporter/common/DashItemList.py
  synfig-studio/plugins/lottie-exporter/common/Hermite.py
  synfig-studio/plugins/lottie-exporter/common/Makefile.am
  synfig-studio/plugins/lottie-exporter/common/Vector.py
  synfig-studio/plugins/lottie-exporter/common/WidthPoint.py
  synfig-studio/plugins/lottie-exporter/common/WidthPointList.py
  synfig-studio/plugins/lottie-exporter/properties/shapeKeyframed.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/Makefile.am
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/helper.py
  synfig-studio/plugins/lottie-exporter/settings.py
Labels: Export

#2210 [Synfig Studio] Middle click on a tab now closes the root canvas only when all child canvases are closed
  synfig-studio/src/gui/docks/dockbook.cpp
Labels: Bug

#2209 [Studio] Fixed crash in rare cases caused by race condition when rebuilding LayerTreeStore
  synfig-studio/src/gui/trees/layertreestore.cpp
  synfig-studio/src/gui/trees/layertreestore.h
Labels: Bug, Crash

#2134 [Core] Fixed incorrect background restoration on animated GIFs with transparent background
  synfig-core/src/modules/mod_gif/trgt_gif.cpp
Labels: Backport, Bug

#2234 [Studio] Fixed crash in debug builds when right-clicking on some waypoints
  synfig-studio/src/gui/widgets/widget_waypoint.cpp
Labels: Crash

#2233 [Lottie exporter] Add animation to addition/deletion of Width points and Dash items in advanced outline
  synfig-studio/plugins/lottie-exporter/CMakeLists.txt
  synfig-studio/plugins/lottie-exporter/canvas.py
  synfig-studio/plugins/lottie-exporter/common/Activepoint.py
  synfig-studio/plugins/lottie-exporter/common/ActivepointList.py
  synfig-studio/plugins/lottie-exporter/common/DashItemList.py
  synfig-studio/plugins/lottie-exporter/common/Makefile.am
  synfig-studio/plugins/lottie-exporter/common/WidthPoint.py
  synfig-studio/plugins/lottie-exporter/common/WidthPointList.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
Labels: Export, Plugins

#2237 Disabled some Travis CI build jobs
  .travis.yml
Labels: infrastructure

#2238 Added Synfig tests to Github CI workflow
  .github/workflows/synfig-tests.yml
Labels: infrastructure

#2236 [Lottie exporter] Add animation to addtion/deletion of Bline points
  synfig-studio/plugins/lottie-exporter/CMakeLists.txt
  synfig-studio/plugins/lottie-exporter/common/Activepoint.py
  synfig-studio/plugins/lottie-exporter/common/ActivepointList.py
  synfig-studio/plugins/lottie-exporter/common/Angle.py
  synfig-studio/plugins/lottie-exporter/common/Bline.py
  synfig-studio/plugins/lottie-exporter/common/BlinePoint.py
  synfig-studio/plugins/lottie-exporter/common/Makefile.am
  synfig-studio/plugins/lottie-exporter/common/Vector.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/constant_width_outline.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/helper.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/outline.py
  synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/region.py
  synfig-studio/plugins/lottie-exporter/settings.py
  synfig-studio/plugins/lottie-exporter/synfig/animation.py
Labels: Export, Plugins

#2213 [Synfig Studio] The end time in the render settings is now correctly updated when changed from the toolbar
  synfig-studio/src/gui/canvasview.cpp
Labels: Bug, GUI

#2239 [Studio] Fixed a crash when trying to import a file into itself
  synfig-studio/src/gui/canvasview.cpp
Labels: Backport, Crash
