Repository synfig/synfig, pull requests merged in 2021-11, with the labels that each got.

#2399 ETL cleanup: remove unused files and deprecated functions
  ETL/ETL/CMakeLists.txt
  ETL/ETL/Makefile.am
  ETL/ETL/_angle.h
  ETL/ETL/_bezier.h
  ETL/ETL/_bezier_angle.h
  ETL/ETL/_curve_func.h
  ETL/ETL/_fixed.h
  ETL/ETL/angle
  ETL/ETL/bezier
  ETL/ETL/etl_config.h
  ETL/ETL/fixed
  ETL/test/benchmark.cpp
  ETL/test/hermite.cpp
  synfig-core/src/synfig/blur.cpp
Labels: Code quality

#2394 Svg_parser: fix command 'a' for Path element: ellipse arcs work now
  synfig-core/src/modules/mod_svg/svg_parser.cpp
Labels: Enhancement

#2386 support MLT 7 for CMake build system
  synfig-core/src/CMakeLists.txt
  synfig-studio/src/CMakeLists.txt
Labels: CMake

#2389 Fixed crash when rendering to gif target
  synfig-core/src/modules/mod_gif/trgt_gif.cpp
Labels: Crash

#2401 Svg_parser: cleanups and some outline-related fixes
  synfig-core/src/modules/mod_svg/svg_parser.cpp
  synfig-core/src/modules/mod_svg/svg_parser.h
Labels: Code quality

#2404 Tab/Shift-Tab support for Widget_Vector
  synfig-studio/src/gui/widgets/widget_vector.cpp
  synfig-studio/src/gui/widgets/widget_vector.h
Labels: UI/UX

#2296 move layer and valuenode iteration methods to synfig-core
  synfig-core/po/POTFILES.in
  synfig-core/src/synfig/CMakeLists.txt
  synfig-core/src/synfig/Makefile.am
  synfig-core/src/synfig/synfig_iterations.cpp
  synfig-core/src/synfig/synfig_iterations.h
  synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
  synfig-core/src/synfig/valuenodes/valuenode_bone.h
  synfig-core/src/synfig/valuenodes/valuenode_staticlist.cpp
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
Labels: Code quality

#2395 Clear Redo History on new action by default; new user preference
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.h
  synfig-studio/src/gui/instance.cpp
Labels: Enhancement

#2418 Svg_parser: remove unused properties & method, restrict var scope
  synfig-core/src/modules/mod_svg/svg_parser.cpp
  synfig-core/src/modules/mod_svg/svg_parser.h
Labels: Code quality

#2416 Linux build: Autodetect number of threads for compilation
  autobuild/build.sh
Labels: Linux, Enhancement

#2414 Add completion to Widget_FontFamily
  synfig-studio/src/gui/widgets/widget_fontfamily.cpp
Labels: Enhancement, UI/UX

#2420 don't let user drag a waypoint to a time lower than current minimum
  synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
  synfig-studio/src/gui/widgets/widget_curves.cpp
  synfig-studio/src/gui/widgets/widget_timetrack.cpp
Labels: UI/UX

#2421 move variable closer to its use and rename it to avoid confusion
  synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
Labels: Code quality

#2189 Usability tweaks
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/docks/dock_toolbox.cpp
  synfig-studio/src/gui/docks/dockable.cpp
  synfig-studio/src/gui/mainwindow.cpp
  synfig-studio/src/synfigapp/actions/valuedescexport.cpp
Labels: Code quality

#2422 Parameters and Timeline panels show the same row selected
  synfig-studio/src/gui/docks/dock_timetrack.cpp
Labels: Enhancement, GUI, UI/UX, Backport

#2433 Allow Bones parameters to be connected to exported value nodes
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/loadcanvas.h
Labels: Bones

#2432 fix compilation warning for unused parameters on valuenode methods
  synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
  synfig-core/src/synfig/valuenodes/valuenode_boneinfluence.cpp
  synfig-core/src/synfig/valuenodes/valuenode_boneinfluence.h
  synfig-core/src/synfig/valuenodes/valuenode_boneweightpair.cpp
  synfig-core/src/synfig/valuenodes/valuenode_boneweightpair.h
  synfig-core/src/synfig/valuenodes/valuenode_duplicate.cpp
  synfig-core/src/synfig/valuenodes/valuenode_timeloop.cpp
Labels: Code quality

#2429 Svg_parser: primitive rect properly uses style
  synfig-core/src/modules/mod_svg/svg_parser.cpp
Labels: Enhancement

#2402 Fix distance values on settings
  synfig-studio/src/gui/states/state_bline.cpp
  synfig-studio/src/gui/states/state_bone.cpp
  synfig-studio/src/gui/states/state_circle.cpp
  synfig-studio/src/gui/states/state_draw.cpp
  synfig-studio/src/gui/states/state_lasso.cpp
  synfig-studio/src/gui/states/state_polygon.cpp
  synfig-studio/src/gui/states/state_rectangle.cpp
  synfig-studio/src/gui/states/state_star.cpp
  synfig-studio/src/gui/states/state_width.cpp
  synfig-studio/src/synfigapp/settings.cpp
  synfig-studio/src/synfigapp/settings.h
Labels: Bug

#2428 [CMake] Improved search for libraries
  synfig-core/src/CMakeLists.txt
  synfig-core/src/modules/CMakeLists.txt
  synfig-core/src/modules/lyr_std/CMakeLists.txt
  synfig-core/src/modules/mod_dv/CMakeLists.txt
  synfig-core/src/modules/mod_geometry/CMakeLists.txt
  synfig-core/src/modules/mod_jpeg/CMakeLists.txt
  synfig-core/src/modules/mod_magickpp/CMakeLists.txt
  synfig-core/src/modules/mod_noise/CMakeLists.txt
  synfig-core/src/modules/mod_openexr/CMakeLists.txt
  synfig-core/src/modules/mod_png/CMakeLists.txt
  synfig-core/src/modules/mod_svg/CMakeLists.txt
  synfig-core/src/synfig/CMakeLists.txt
  synfig-core/src/synfig/valuenodes/CMakeLists.txt
  synfig-core/src/tool/CMakeLists.txt
Labels: CMake

#2425 Fixed build warnings
  synfig-core/src/synfig/filesystemnative.h
  synfig-core/src/synfig/rendering/software/function/blur.cpp
  synfig-core/src/synfig/target_multi.cpp
  synfig-core/src/synfig/target_multi.h
  synfig-core/src/synfig/valuenodes/valuenode_radialcomposite.cpp
  synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
  synfig-studio/src/gui/dialogs/canvasoptions.h
  synfig-studio/src/gui/dialogs/dialog_workspaces.h
  synfig-studio/src/gui/widgets/widget_vector.cpp
  synfig-studio/src/gui/widgets/widget_vector.h
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
Labels: Code quality

#2441 [CMake] Improved libmng search
  synfig-core/src/modules/mod_mng/CMakeLists.txt
Labels: CMake

#2445 Fixed crash when using Draw tool (Fedora/Flatpak)
  CMakeLists.txt
  synfig-studio/src/synfigapp/blineconvert.cpp
Labels: Bug, Crash, CMake
