Repository synfig/synfig, pull requests merged in 2021-01, with the labels that each got.

#1964 [CMake] Fixed issue with CMake generating file inside source tree when using out-of-source build
  synfig-core/src/modules/CMakeLists.txt
Labels: CMake

#1968 [Synfig Studio] Waypoint Editor didn't properly support enums
  synfig-studio/src/gui/dialogs/dialog_waypoint.cpp
  synfig-studio/src/gui/widgets/widget_waypoint.cpp
  synfig-studio/src/gui/widgets/widget_waypoint.h
Labels: Backport

#1973 [Synfig Studio] fix mainwindow not showing when is offscreen
  synfig-studio/src/gui/docks/dockmanager.cpp
Labels: Backport

#1981 autotools: fix POTFILES.in again and Makefile.am
  synfig-studio/po/POTFILES.in
  synfig-studio/src/synfigapp/Makefile.am
Labels: Backport

#1977 [Synfig Studio] Bumped year in About dialog
  synfig-studio/src/gui/dialogs/about.cpp
Labels: Backport, GUI

#1982 [Autotools] Fixed problem with missing *.glsl files in distribution
  synfig-core/src/synfig/rendering/opengl/internal/glsl/Makefile_insert
Labels: Backport

#1945 [Synfig Studio] Make Preview tooltips and titles consistent with other dialogs
  synfig-studio/src/gui/dialogs/dialog_preview.cpp
  synfig-studio/src/gui/dials/framedial.cpp
  synfig-studio/src/gui/preview.cpp
  synfig-studio/src/gui/resources/ui/preview_options.glade
Labels: GUI

#2000 [Core] fix missing is_distance hint for vertex coordinates
  synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
Labels: Backport
