Repository synfig/synfig, pull requests merged in 2021-10, with the labels that each got.

#2325 [Studio] Bone Tool cleanup
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Code quality

#2232 Add better support for Arabic language to Text Layer
  1-setup-linux-native.sh
  synfig-core/configure.ac
  synfig-core/src/CMakeLists.txt
  synfig-core/src/modules/lyr_freetype/CMakeLists.txt
  synfig-core/src/modules/lyr_freetype/Makefile.am
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-core/src/modules/lyr_freetype/lyr_freetype.h
  synfig-core/src/synfig/CMakeLists.txt
  synfig-studio/src/CMakeLists.txt
Labels: Text

#2343 Bone Tool: fix default bone width preference loading
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Bug

#2265 Fixed crash of test on Void Linux
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
Labels: Crash
