Repository synfig/synfig, pull requests merged in 2021-05, with the labels that each got.

#2135 [CMake] Fixed ETL tests
  CMakeLists.txt
  ETL/CMakeLists.txt
  ETL/test/CMakeLists.txt
Labels: CMake

#1476 Added the ability to create Plant and Curve Gradient layer from other Splines [Synfig Studio]
  synfig-studio/src/synfigapp/action.cpp
  synfig-studio/src/synfigapp/actions/layermakebline.cpp
  synfig-studio/src/synfigapp/actions/layermakebline.h
Labels: Enhancement, GUI

#2138 [CMake] Synfig now builds correctly on any system without MLT library
  CMakeLists.txt
  synfig-core/src/CMakeLists.txt
  synfig-studio/src/CMakeLists.txt
Labels: CMake

#2146 [MacOS] Removed unnecessary pip installation
  1-setup-osx-brew.sh
Labels: MacOS

#2129 [CMake] Removed unnecessary dependencies in modules
  synfig-core/src/modules/lyr_freetype/CMakeLists.txt
  synfig-core/src/modules/lyr_std/CMakeLists.txt
  synfig-core/src/modules/mod_bmp/CMakeLists.txt
  synfig-core/src/modules/mod_dv/CMakeLists.txt
  synfig-core/src/modules/mod_example/CMakeLists.txt
  synfig-core/src/modules/mod_ffmpeg/CMakeLists.txt
  synfig-core/src/modules/mod_filter/CMakeLists.txt
  synfig-core/src/modules/mod_geometry/CMakeLists.txt
  synfig-core/src/modules/mod_gif/CMakeLists.txt
  synfig-core/src/modules/mod_gradient/CMakeLists.txt
  synfig-core/src/modules/mod_imagemagick/CMakeLists.txt
  synfig-core/src/modules/mod_jpeg/CMakeLists.txt
  synfig-core/src/modules/mod_magickpp/CMakeLists.txt
  synfig-core/src/modules/mod_mng/CMakeLists.txt
  synfig-core/src/modules/mod_noise/CMakeLists.txt
  synfig-core/src/modules/mod_openexr/CMakeLists.txt
  synfig-core/src/modules/mod_particle/CMakeLists.txt
  synfig-core/src/modules/mod_png/CMakeLists.txt
  synfig-core/src/modules/mod_ppm/CMakeLists.txt
  synfig-core/src/modules/mod_svg/CMakeLists.txt
  synfig-core/src/modules/mod_yuv420p/CMakeLists.txt
Labels: CMake

#2145 `1-setup-linux-native.sh` script now supports PipeWire
  1-setup-linux-native.sh
Labels: Linux, infrastructure

#2156 Improved error reporting [studio]
  synfig-studio/src/gui/app.cpp
Labels: Code quality

#2157 Fixed 'locale::facet::_S_create_c_locale name not valid' error when compiling with MinGW compiler
  synfig-core/src/synfig/string_helper.cpp
Labels: Bug, Windows

#2165 Fixed issue with saving `loop` flag in some dynamic lists (Such as `average` and `weighted_average`)
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/savecanvas.cpp
Labels: Bug

#2159 Fixed `mod_dv` build with MSVC compiler
  synfig-core/src/modules/mod_dv/trgt_dv.cpp
  synfig-core/src/modules/mod_dv/trgt_dv.h
Labels: Windows

#1958 [Synfig Studio] Split top horizontal toolbar in two toolbars (horizontal+vertical)
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
Labels: GUI
