Repository synfig/synfig, pull requests merged in 2021-12, with the labels that each got.

#2442 Change #include to not... include... harfbuzz or fribidi folder
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-core/src/modules/lyr_freetype/lyr_freetype.h
Labels: Code quality

#2439 Added ability to import multiple files
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/app.h
  synfig-studio/src/gui/canvasview.cpp
Labels: Enhancement

#2457 Bone Tool: Correctly apply offset to Second bone when First bone changed
  synfig-studio/src/synfigapp/actions/valuedescset.cpp
Labels: Bones

#2464 Fixed appdata.xml check CI
  .github/workflows/synfig-tests.yml
Labels: infrastructure

#2453 Refactored SynfigToolGeneralOptions singleton
  synfig-core/src/tool/definitions.cpp
  synfig-core/src/tool/definitions.h
  synfig-core/src/tool/main.cpp
Labels: Code quality

#2424 [MacOS M1] Fixed autotools build
  autobuild/build.sh
Labels: MacOS

#2458 ValueDescSet Skeleton Deformation bone: minor refactoring
  synfig-studio/src/synfigapp/actions/valuedescset.cpp
Labels: Bones

#2466 Fix bone width handle visibility
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Bones

#2455 Added ability for escape key to close editing box in Value column in the Parameters panel
  synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
Labels: Enhancement, GUI

#2470 fix my mistake in #2458: it should not return at that point
  synfig-studio/src/synfigapp/actions/valuedescset.cpp
Labels: Bones

#2477 Fix exported file with audio being smaller than it should
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Labels: Backport

#2471 fix distortions at the end of lines made with the drawing tool
  synfig-studio/src/synfigapp/blineconvert.cpp
Labels: Bug

#2463 Make sure flags are correctly updated when setting renddesc
  synfig-studio/src/gui/renddesc.cpp
  synfig-studio/src/gui/renddesc.h
Labels: GUI

#2473 Svg_parser: fix not creating last vertex of cubic path segment
  synfig-core/src/modules/mod_svg/svg_parser.cpp
Labels: SVG

#2468 BoneLink: Ask user if s/he wants to use transformation instead of origin
  synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
Labels: Bones

#2482 loadcanvas: fix loading of some non-value nodes lists
  synfig-core/src/synfig/loadcanvas.cpp
Labels: Bug

#2485 fix regression on loading and saving of settings Distance type (i18n)
  synfig-studio/src/synfigapp/settings.cpp
Labels: Regression

#2484 Bone Tool:remove deprecated method set_alignment that use default values
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Code quality

#2483 Bone Tool: fix regression on Bone width auto change requested in #1658
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Regression
