Repository synfig/synfig, pull requests merged in 2021-09, with the labels that each got.

#2292 Replaced using std/etl namespaces with explicit namespace name
  ETL/test/handle.cpp
  ETL/test/smart_ptr.cpp
  synfig-core/src/synfig/blur.cpp
  synfig-core/src/synfig/color/color.cpp
  synfig-core/src/synfig/curve_helper.cpp
  synfig-core/src/synfig/distance.cpp
  synfig-core/src/synfig/filesystemtemporary.cpp
  synfig-core/src/synfig/importer.cpp
  synfig-core/src/synfig/layer.cpp
  synfig-core/src/synfig/layers/layer_mime.cpp
  synfig-core/src/synfig/module.cpp
  synfig-core/src/synfig/palette.cpp
  synfig-core/src/synfig/polynomial_root.cpp
  synfig-core/src/synfig/savecanvas.cpp
  synfig-core/src/synfig/surface.cpp
  synfig-core/src/synfig/timepointcollect.cpp
  synfig-core/src/synfig/valuenode.cpp
  synfig-core/src/synfig/valuenodes/valuenode_bline.cpp
  synfig-core/src/synfig/valuenodes/valuenode_dynamiclist.cpp
  synfig-core/src/synfig/valuenodes/valuenode_gradientrotate.cpp
  synfig-core/src/synfig/valuenodes/valuenode_join.cpp
  synfig-core/src/synfig/valuenodes/valuenode_radialcomposite.cpp
  synfig-core/src/synfig/valuenodes/valuenode_range.cpp
  synfig-core/src/synfig/valuenodes/valuenode_real.cpp
  synfig-core/src/synfig/valuenodes/valuenode_repeat_gradient.cpp
  synfig-core/src/synfig/valuenodes/valuenode_scale.cpp
  synfig-core/src/synfig/valuenodes/valuenode_staticlist.cpp
  synfig-core/src/synfig/valuenodes/valuenode_stripes.cpp
  synfig-core/src/synfig/valuenodes/valuenode_subtract.cpp
  synfig-core/src/synfig/valuenodes/valuenode_weightedaverage.cpp
  synfig-core/src/synfig/valuenodes/valuenode_wplist.cpp
  synfig-studio/src/gui/duckmatic.cpp
  synfig-studio/src/gui/keymapsettings.cpp
  synfig-studio/src/gui/preview.cpp
  synfig-studio/src/gui/render.cpp
  synfig-studio/src/gui/states/state_bone.cpp
  synfig-studio/src/gui/states/state_brush.cpp
  synfig-studio/src/gui/states/state_draw.cpp
  synfig-studio/src/gui/states/state_lasso.cpp
  synfig-studio/src/gui/states/state_normal.cpp
  synfig-studio/src/gui/states/state_rotate.cpp
  synfig-studio/src/gui/states/state_scale.cpp
  synfig-studio/src/gui/states/state_width.cpp
  synfig-studio/src/gui/states/state_zoom.cpp
  synfig-studio/src/gui/trees/canvastreestore.cpp
  synfig-studio/src/gui/trees/layergrouptreestore.cpp
  synfig-studio/src/gui/widgets/widget_filename.cpp
  synfig-studio/src/gui/widgets/widget_sublayer.cpp
  synfig-studio/src/gui/workarea.cpp
  synfig-studio/src/synfigapp/inputdevice.cpp
  synfig-studio/src/synfigapp/instance.cpp
  synfig-studio/src/synfigapp/main.cpp
Labels: Code quality

#2298 [Studio] remove unused classes
  synfig-studio/po/POTFILES.in
  synfig-studio/src/gui/CMakeLists.txt
  synfig-studio/src/gui/Makefile.am
  synfig-studio/src/gui/audiocontainer.cpp
  synfig-studio/src/gui/audiocontainer.h
  synfig-studio/src/gui/valuelink.cpp
  synfig-studio/src/gui/valuelink.h
Labels: Code quality

#2312 Added the ability to add a new vertex on a Spline by double-click
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
  synfig-studio/src/gui/duckmatic.cpp
  synfig-studio/src/gui/duckmatic.h
  synfig-studio/src/gui/workarea.cpp
Labels: UI/UX

#2308 When the user imports the file, the imported layer becomes selected
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/synfigapp/canvasinterface.cpp
  synfig-studio/src/synfigapp/canvasinterface.h
Labels: UI/UX

#2322 Switched Ubuntu version on Github Workflows to 18.04
  .github/workflows/synfig-ci.yml
  .github/workflows/synfig-stable.yml
Labels: infrastructure

#2314 [core] Improve hints for Dash item parameters
  synfig-core/src/modules/mod_geometry/advanced_outline.cpp
  synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
Labels: UI/UX

#2324 Fix magick++ target missing in AppImage
  synfig-core/src/modules/mod_magickpp/Makefile.am
Labels: Backport

#2315 Minor cleanup in CreateChildBone action
  synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp
  synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
Labels: Code quality

#2309 [Studio] Fix dialog responses when user pressing Esc key
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
  synfig-studio/src/gui/instance.cpp
Labels: UI/UX

#2291 Made shared_objects non-copyable
  ETL/ETL/_handle.h
  synfig-core/src/modules/lyr_std/perspective.cpp
  synfig-core/src/synfig/rendering/primitive/transformationaffine.h
Labels: Code quality

#2329 Fix *again* dialog responses. Mistakes made in 5ffa7928dd55ae66f77b8e…
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
Labels: Critical, Regression

#2333 Fix regression: importing image making it upside-down
  synfig-studio/src/synfigapp/canvasinterface.cpp
Labels: Bug
