Repository synfig/synfig, pull requests merged in 2021-02, with the labels that each got.

#1940 [Synfig Studio/Windows] Fixed issue with rendering to file when using non-Latin filenames
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
  synfig-core/src/tool/joblistprocessor.cpp
  synfig-studio/src/gui/render.cpp
Labels: Backport, Windows

#1955 [Synfig Core] Added support for loading `average` values
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/valuenodes/valuenode_average.cpp
  synfig-core/src/synfig/valuenodes/valuenode_average.h
Labels: Backport

#1929 [Synfig Studio] Added ability to undock panel using the context menu command
  synfig-studio/src/gui/docks/dockable.cpp
  synfig-studio/src/gui/docks/dockable.h
  synfig-studio/src/gui/docks/dockbook.cpp
Labels: GUI

#1971 [Synfig Studio] Fix action LayerDuplicate with layers "duplicate" o.O
  synfig-studio/Makefile.am
  synfig-studio/configure.ac
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
  synfig-studio/src/synfigapp/actions/layerduplicate.h
  synfig-studio/src/synfigapp/actions/valuenodeadd.cpp
  synfig-studio/src/synfigapp/canvasinterface.cpp
  synfig-studio/test/Makefile.am
  synfig-studio/test/app_layerduplicate.cpp
Labels: Backport

#1988 [Synfig Studio] fix "Link to Spline" showing when a vertex of spline itself is selected
  synfig-studio/src/synfigapp/actions/valuedescblinelink.cpp
Labels: Backport

#1997 [Core/Studio] Added support for user-installed fonts on Windows 10 (1809)
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-studio/src/gui/widgets/widget_fontfamily.cpp
  synfig-studio/src/gui/widgets/widget_fontfamily.h
Labels: Backport, Windows

#2011 [ETL] current_working_directory() function now works correctly with non-Latin filenames
  ETL/ETL/_stringf.h
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Labels: Backport, Windows

#2031 [Synfig Studio] Turn off color dialog's resizability
  synfig-studio/src/gui/dialogs/dialog_color.cpp
Labels: GUI

#2029 [Core] assure uniqueness for new node guid
  synfig-core/src/synfig/node.cpp
Labels: Backport

#2043 [Synfig Studio] avoid dereference of invalid TreeIter on Layer TreeView
  synfig-studio/src/gui/trees/layertree.cpp
Labels: Backport

#2019 [Synfig Studio] Noticeable progress bar
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/resources/css/synfig.css
Labels: GUI

#2050 [Synfig Studio] don't let inner layer be duplicated twice
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
  synfig-studio/test/app_layerduplicate.cpp
Labels: Backport, Crash
