Repository synfig/synfig, pull requests merged in 2021-08, with the labels that each got.

#2249 Updated snap to 1.4.2
  autobuild/snap-stable/snapcraft.yaml
Labels: infrastructure

#2243 [Studio] Fixed issue with non-working import when importing to unsaved SIF file
  synfig-studio/src/gui/canvasview.cpp
Labels: Bug

#2269 Update release scripts
  version-release.sh
Labels: infrastructure

#2252 [Studio] fix image size when importing onto canvas with non-standard size
  synfig-studio/src/synfigapp/canvasinterface.cpp
Labels: Backport

#2278 Fix "files left after uninstall" error for "distuninstallcheck" target
  ETL/configure.ac
  ETL/test/Makefile.am
  ETL/test/handle.cpp
  ETL/test/pen.cpp
  synfig-studio/images/Makefile.am
Labels: Backport

#2282 Extracted layer size update as a separate function
  synfig-studio/src/synfigapp/canvasinterface.cpp
Labels: Code quality
