Repository synfig/synfig, pull requests merged in 2022-03, with the labels that each got.

#2550 fix layer Clamp not rendering
  synfig-core/src/modules/lyr_std/clamp.cpp
Labels: Backport

#2535 Fix Bone Shape of Skeleton Deformation affected by Transformations
  synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.cpp
Labels: Bones

#2560 ensure computed GUID is not zero
  synfig-core/src/synfig/guid.cpp
Labels: Code quality

#2559 add more synfig::Node tests
  synfig-core/test/node.cpp
Labels: tests

#2552 Simplify "Render Mode ComboBox Changed" callback & add GL if available
  synfig-studio/src/gui/canvasview.cpp
Labels: Code quality

#2504 eliminate the need to set_time() on the search for bones
  synfig-studio/src/synfigapp/actions/layerduplicate.cpp
Labels: Code quality

#2563 FFmpeg targets: allow to render alpha channel for webm and hap videos
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.h
Labels: Feature request

#2566 [MSYS2] Updated packages list
  1-setup-windows-msys2.sh
Labels: Windows

#2576 [MSYS2] Removed patch for libintl
  1-setup-windows-msys2.sh
  autobuild/msys2/libintl.h.patch
Labels: Windows

#2574 fix RendDesc::get_pixels_to_world_matrix() contents
  synfig-core/src/synfig/renddesc.h
Labels: Bug

#2568 add new ValueNode "Modulo" for modulo operation
  synfig-core/po/POTFILES.in
  synfig-core/src/synfig/releases.h
  synfig-core/src/synfig/valuenodes/CMakeLists.txt
  synfig-core/src/synfig/valuenodes/Makefile_insert
  synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
  synfig-core/src/synfig/valuenodes/valuenode_modulo.cpp
  synfig-core/src/synfig/valuenodes/valuenode_modulo.h
Labels: Feature request

#2578 simplify Widget_Sublayer by using Gtk::ComboBoxText
  synfig-studio/src/gui/widgets/widget_sublayer.cpp
  synfig-studio/src/gui/widgets/widget_sublayer.h
Labels: GUI

#2567 Added the ability to select the parent layer through the keyboard shortcut (Alt+Page Up)
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
Labels: GUI, UI/UX

#2575 [MSYS2] Fixed MSYS2 dependencies
  1-setup-windows-msys2.sh
Labels: Windows, infrastructure

#2581 Added hotkey for grouping layers (Ctrl+G). Grid toggle hotkey changed to #.
  synfig-studio/src/gui/app.cpp
Labels: UI/UX

#2570 Fixed bug with src offset in blur sw task
  synfig-core/src/synfig/rendering/software/function/blur.cpp
Labels: Bug, Crash

#2573 Added the ability to set the build type from the command line to the 2-build-msys-cmake.sh script
  2-build-msys-cmake.sh
Labels: infrastructure

#2583 improve output readability of unit tests with test_base.h
  synfig-core/test/bline.cpp
  synfig-core/test/node.cpp
  synfig-core/test/test_base.h
Labels: Code quality
