Repository synfig/synfig, pull requests merged in 2022-05, with the labels that each got.

#2621 Fix module search path for Lottie Exporter
  synfig-studio/plugins/lottie-exporter/lottie-exporter.py
Labels: Backport

#2623 Bumped year
  autobuild/osx/app-template/Contents/Info.plist
  synfig-studio/src/gui/dialogs/about.cpp
Labels: GUI, Backport

#2602 [CMake] Added option to link with tcmalloc library
  CMakeLists.txt
  synfig-core/src/tool/CMakeLists.txt
  synfig-studio/src/gui/CMakeLists.txt
Labels: CMake

#2587 Fix crash when deleting last waypoint
  synfig-studio/src/synfigapp/value_desc.cpp
  synfig-studio/src/synfigapp/value_desc.h
Labels: Crash

#2628 Fixed video render with FFmpeg version 3
  synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Labels: Bug

#2631 Fix typo in source
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
Labels: Typos

#2632 Added basic support for Gtk theme
  synfig-studio/images/CMakeLists.txt
  synfig-studio/images/Makefile.am
  synfig-studio/images/index.theme
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/app.h
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.h
  synfig-studio/src/gui/docks/dialog_tooloptions.cpp
  synfig-studio/src/gui/docks/dialog_tooloptions.h
  synfig-studio/src/gui/docks/dock_canvases.cpp
  synfig-studio/src/gui/docks/dock_canvasspecific.cpp
  synfig-studio/src/gui/docks/dock_canvasspecific.h
  synfig-studio/src/gui/docks/dock_children.cpp
  synfig-studio/src/gui/docks/dock_curves.cpp
  synfig-studio/src/gui/docks/dock_history.cpp
  synfig-studio/src/gui/docks/dock_info.cpp
  synfig-studio/src/gui/docks/dock_keyframes.cpp
  synfig-studio/src/gui/docks/dock_layergroups.cpp
  synfig-studio/src/gui/docks/dock_layers.cpp
  synfig-studio/src/gui/docks/dock_metadata.cpp
  synfig-studio/src/gui/docks/dock_navigator.cpp
  synfig-studio/src/gui/docks/dock_params.cpp
  synfig-studio/src/gui/docks/dock_soundwave.cpp
  synfig-studio/src/gui/docks/dock_timetrack.cpp
  synfig-studio/src/gui/docks/dock_timetrack2.cpp
  synfig-studio/src/gui/docks/dock_toolbox.cpp
  synfig-studio/src/gui/docks/dockable.cpp
  synfig-studio/src/gui/docks/dockable.h
  synfig-studio/src/gui/docks/dockbook.cpp
  synfig-studio/src/gui/iconcontroller.cpp
  synfig-studio/src/gui/iconcontroller.h
  synfig-studio/src/gui/instance.cpp
  synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
  synfig-studio/src/gui/resourcehelper.cpp
  synfig-studio/src/gui/resourcehelper.h
  synfig-studio/src/gui/splash.cpp
  synfig-studio/src/gui/states/state_bline.cpp
  synfig-studio/src/gui/states/state_brush.cpp
  synfig-studio/src/gui/states/state_circle.cpp
  synfig-studio/src/gui/states/state_draw.cpp
  synfig-studio/src/gui/states/state_gradient.cpp
  synfig-studio/src/gui/states/state_lasso.cpp
  synfig-studio/src/gui/states/state_mirror.cpp
  synfig-studio/src/gui/states/state_normal.cpp
  synfig-studio/src/gui/states/state_polygon.cpp
  synfig-studio/src/gui/states/state_rectangle.cpp
  synfig-studio/src/gui/states/state_rotate.cpp
  synfig-studio/src/gui/states/state_scale.cpp
  synfig-studio/src/gui/states/state_sketch.cpp
  synfig-studio/src/gui/states/state_smoothmove.cpp
  synfig-studio/src/gui/states/state_star.cpp
  synfig-studio/src/gui/states/state_text.cpp
  synfig-studio/src/gui/states/state_width.cpp
Labels: GUI

#2495 fix regression: importing papagayo file didn't show the expected layers
  synfig-studio/src/gui/trees/layertreestore.cpp
Labels: Critical, Backport, Regression

#2638 Added Synfig Studio menu and UI files
  synfig-studio/src/gui/resources/ui/CMakeLists.txt
  synfig-studio/src/gui/resources/ui/file_top_toolbar.glade
  synfig-studio/src/gui/resources/ui/history_toolbar.glade
  synfig-studio/src/gui/resources/ui/right_toolbar.glade
  synfig-studio/src/gui/resources/ui/studio_menubar.xml
  synfig-studio/src/gui/resources/ui/top_toolbar.glade
Labels: Code quality

#2640 Fixed missing icons in tool options
  synfig-studio/src/gui/states/state_bline.cpp
  synfig-studio/src/gui/states/state_circle.cpp
  synfig-studio/src/gui/states/state_draw.cpp
  synfig-studio/src/gui/states/state_gradient.cpp
  synfig-studio/src/gui/states/state_lasso.cpp
  synfig-studio/src/gui/states/state_polygon.cpp
  synfig-studio/src/gui/states/state_rectangle.cpp
  synfig-studio/src/gui/states/state_star.cpp
  synfig-studio/src/gui/states/state_text.cpp
Labels: GUI

#2645 Returned back the ability to set a GTK theme using an environment variable
  synfig-studio/src/gui/app.cpp
Labels: dark theme

#2064 [Studio] Hide "Make Parent To Active Bone" menu item when not using Skeleton Tool
  synfig-studio/src/gui/instance.cpp
  synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp
  synfig-studio/src/synfigapp/actions/valuedescbonesetparent.h
Labels: GUI

#2651 Fixed an issue with plugins not working when path to Python contains spaces (Windows)
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/app.h
Labels: Windows

#2657 Fixed issue with python search on Ubuntu 18
  synfig-studio/src/gui/app.cpp
Labels: Bug

#2509 fix behavior after Tool process a key event: only proceeds when RESULT_OK
  synfig-studio/src/gui/_smach.h
  synfig-studio/src/gui/states/state_normal.cpp
  synfig-studio/src/gui/workarea.cpp
Labels: Code quality

#2653 Fixed incorrect lines offset in Graphs Panel
  synfig-studio/src/gui/widgets/widget_curves.cpp
Labels: GUI

#2658 Refactored python search algorithm
  synfig-studio/src/gui/pluginmanager.cpp
Labels: Code quality
