Repository synfig/synfig, pull requests merged in 2022-04, with the labels that each got.

#2603 Switched Ubuntu version on Github Workflows to 18.04 (#2322)
  .github/workflows/synfig-ci.yml
  .github/workflows/synfig-stable.yml
Labels: infrastructure

#2600 update contributor name list
  synfig-studio/src/gui/dialogs/about.cpp
Labels: GUI

#2601 Update contributor name list
  synfig-studio/src/gui/dialogs/about.cpp
Labels: GUI

#2591 Fix crash when switching workspaces
  synfig-studio/src/gui/docks/dockmanager.cpp
Labels: Bug

#2616 remove old .cvsignore files
  synfig-osx/launcher/.cvsignore
  synfig-osx/launcher/English.lproj/.cvsignore
  synfig-osx/launcher/Synfig Studio.pbproj/.cvsignore
  synfig-osx/launcher/utils/.cvsignore
Labels: Code quality
