Repository synfig/synfig, pull requests merged in 2022-02, with the labels that each got.

#2524 Fixed PVS-Studio warning v656
  synfig-core/src/synfig/valuenodes/valuenode_bonelink.cpp
  synfig-studio/src/gui/states/state_bline.cpp
  synfig-studio/src/gui/states/state_circle.cpp
  synfig-studio/src/gui/states/state_polygon.cpp
  synfig-studio/src/gui/states/state_rectangle.cpp
  synfig-studio/src/gui/states/state_star.cpp
Labels: Code quality

#2520 Removed "using namespace std;"
  ETL/test/pen.cpp
  ETL/test/stringf.cpp
  synfig-core/src/modules/mod_ffmpeg/mptr_ffmpeg.cpp
  synfig-core/src/modules/mod_png/trgt_png_spritesheet.cpp
  synfig-core/src/synfig/canvas.cpp
  synfig-core/src/synfig/curveset.cpp
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/rendering/software/function/blur.cpp
  synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
  synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
  synfig-core/src/tool/printing_functions.cpp
  synfig-studio/src/gui/instance.cpp
  synfig-studio/src/gui/main.cpp
  synfig-studio/src/gui/main_win32.cpp
  synfig-studio/src/gui/mainwindow.cpp
  synfig-studio/src/gui/widgets/widget_value.cpp
  synfig-studio/src/synfigapp/actions/activepointset.cpp
  synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
  synfig-studio/src/synfigapp/actions/waypointset.cpp
  synfig-studio/src/synfigapp/uimanager.cpp
Labels: Code quality

#2531 Update Installation section in Readme
  README.md
Labels: Documentation

#2518 Quick fix for zstreambuf
  synfig-core/src/synfig/filecontainerzip.cpp
  synfig-core/src/synfig/filesystemtemporary.cpp
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/zstreambuf.cpp
  synfig-core/src/synfig/zstreambuf.h
  synfig-studio/src/gui/instance.cpp
Labels: Enhancement

#2533 remove not-implemented and unused method
  synfig-studio/src/gui/states/state_circle.cpp
Labels: Code quality

#2540 Fixed Synfig Studio crash on exit (MacOS)
  synfig-studio/src/synfigapp/main.cpp
Labels: MacOS, Crash

#2543 create Widget_Interpolation: avoid code duplication and ease maintenance
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/widgets/CMakeLists.txt
  synfig-studio/src/gui/widgets/Makefile_insert
  synfig-studio/src/gui/widgets/widget_interpolation.cpp
  synfig-studio/src/gui/widgets/widget_interpolation.h
  synfig-studio/src/gui/widgets/widget_waypoint.cpp
  synfig-studio/src/gui/widgets/widget_waypointmodel.cpp
Labels: Enhancement

#2542 Added description to FFmpeg units for "Video Bit Rate" field (kbps)
  synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp
Labels: GUI

#2541 [Studio] Added ability to set custom FFmpeg codec
  synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp
Labels: GUI, UI/UX

#2521 Removed tests for `fixed` class
  ETL/test/CMakeLists.txt
  ETL/test/Makefile.am
  ETL/test/benchmark.cpp
  ETL/test/fixed.cpp
  ETL/test/hermite.cpp
Labels: Code quality

#2545 Fixed ETL CMake tests
  ETL/test/CMakeLists.txt
Labels: CMake

#2547 ETL test: avoid clash between ETL::hermite and std::hermite
  ETL/test/angle.cpp
Labels: Backport
