Repository synfig/synfig, pull requests merged in 2022-01, with the labels that each got.

#2486 minor cleanup on TypePair<Bone,Bone> usage
  synfig-studio/src/synfigapp/actions/valuedescset.cpp
Labels: Code quality

#2492 Updated GitHub actions/cache version
  .github/workflows/synfig-ci.yml
Labels: infrastructure

#2487 make UIInterface::confirmation() implementation consistent to signature
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/instance.cpp
  synfig-studio/src/synfigapp/action_system.cpp
  synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
  synfig-studio/src/synfigapp/actions/valuedescset.cpp
Labels: GUI, UI/UX

#2499 Fix hit check for Layer_Freetype
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
  synfig-core/src/modules/lyr_freetype/lyr_freetype.h
  synfig-core/src/synfig/layers/layer_shape.cpp
  synfig-core/src/synfig/layers/layer_shape.h
Labels: Text

#2493 Bone Tool: Fixed issue where skeleton "name" wasn't updated as new Layers are created
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Enhancement, Bones

#2500 fix crash when using Width Tool on Skeleton Layer
  synfig-studio/src/gui/states/state_width.cpp
Labels: Crash

#2505 Fixed issue with opening a file from a network folder on Windows
  synfig-core/src/synfig/filesystemnative.cpp
Labels: Windows, Bug

#2507 Re-enable "Create Child Bone" action
  synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
Labels: UI/UX

#2517 fix Debian 9 building
  synfig-studio/src/brushlib/brush.hpp
Labels: Code quality

#2511 fix error message on Target_Scanline
  synfig-core/src/synfig/target_scanline.cpp
Labels: Code quality

#2515 make "Background" (layer description) string translatable
  synfig-studio/src/gui/app.cpp
Labels: GUI

#2510 FileSystem::Identifier::empty() returned wrong value
  synfig-core/src/synfig/filesystem.h
Labels: Bug

#2523 Fixed PVS-Studio warning v817
  synfig-core/src/modules/mod_svg/svg_parser.cpp
  synfig-core/src/synfig/filesystemtemporary.cpp
  synfig-core/src/synfig/loadcanvas.cpp
  synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
  synfig-core/src/tool/joblistprocessor.cpp
  synfig-core/src/tool/main.cpp
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/dialogs/dialog_setup.cpp
  synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
  synfig-studio/src/gui/docks/dockmanager.cpp
  synfig-studio/src/gui/workspacehandler.cpp
Labels: Code quality

#2467 Show bone shape when Skeleton Deformation layer is disabled
  synfig-studio/po/POTFILES.in
  synfig-studio/src/gui/workarea.cpp
  synfig-studio/src/gui/workarearenderer/CMakeLists.txt
  synfig-studio/src/gui/workarearenderer/Makefile_insert
  synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.cpp
  synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.h
Labels: Bones

#2488 Bone Tool: fix selection of active bone when clicking on a bone duck
  synfig-studio/src/gui/states/state_bone.cpp
Labels: Bones
