Repository synfig/synfig, pull requests merged in 2023-08, with the labels that each got.

#3157 fix: brush tool crashes synfig if no layer is selected in the dialog
  synfig-studio/src/gui/states/state_brush.cpp
Labels: Bug, Backport

#3156 fix: fixed icons in Preferences dialog in Windows
  synfig-studio/src/gui/dialogs/dialog_setup.cpp
Labels: Windows, GUI, Backport

#3164 fix: build on Debian 9
  synfig-core/src/synfig/filesystem_path.cpp
Labels: Compilation

#3163 fix: current time widget color in dark theme
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/resources/css/synfig.css
Labels: GUI

#3178 fix(plugins): crash when selected layers are optional and there is none
  synfig-studio/src/gui/pluginmanager.cpp
Labels: Crash

#3170 fix: toolbox isn't updated when switching document tabs
  synfig-studio/src/gui/docks/dock_toolbox.cpp
  synfig-studio/src/gui/docks/dock_toolbox.h
  synfig-studio/src/gui/statemanager.cpp
  synfig-studio/src/gui/statemanager.h
Labels: Regression

#2562 refactor: port more layers to Cobra renderer: some Gradient layers
  synfig-core/po/POTFILES.in
  synfig-core/src/modules/mod_geometry/checkerboard.cpp
  synfig-core/src/modules/mod_gradient/conicalgradient.cpp
  synfig-core/src/modules/mod_gradient/conicalgradient.h
  synfig-core/src/modules/mod_gradient/lineargradient.cpp
  synfig-core/src/modules/mod_gradient/lineargradient.h
  synfig-core/src/modules/mod_gradient/radialgradient.cpp
  synfig-core/src/modules/mod_gradient/radialgradient.h
  synfig-core/src/modules/mod_gradient/spiralgradient.cpp
  synfig-core/src/modules/mod_gradient/spiralgradient.h
  synfig-core/src/synfig/rendering/software/task/CMakeLists.txt
  synfig-core/src/synfig/rendering/software/task/Makefile_insert
  synfig-core/src/synfig/rendering/software/task/taskpaintpixelsw.cpp
  synfig-core/src/synfig/rendering/software/task/taskpaintpixelsw.h
Labels: Core, Rendering
