Repository synfig/synfig, pull requests merged in 2023-01, with the labels that each got.

#2917 fix: support FontConfig older than version 2.11.91
  synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
Labels: Backport

#2966 chore: bump year to 2023
  autobuild/osx/app-template/Contents/Info.plist
  synfig-studio/src/gui/dialogs/about.cpp
  synfig-studio/src/gui/synfigstudio.rc
Labels: Backport

#1895 feat: simplified canvas resize
  synfig-core/src/synfig/renddesc.cpp
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/canvasview.h
  synfig-studio/src/gui/dialogs/CMakeLists.txt
  synfig-studio/src/gui/dialogs/Makefile_insert
  synfig-studio/src/gui/dialogs/canvasresize.cpp
  synfig-studio/src/gui/dialogs/canvasresize.h
  synfig-studio/src/gui/mainwindow.cpp
  synfig-studio/src/gui/resources/css/CMakeLists.txt
  synfig-studio/src/gui/resources/css/Makefile.am
  synfig-studio/src/gui/resources/css/synfig.css
  synfig-studio/src/gui/resources/css/synfig_dialog.css
  synfig-studio/src/gui/resources/ui/CMakeLists.txt
  synfig-studio/src/gui/resources/ui/Makefile.am
  synfig-studio/src/gui/resources/ui/canvas_resize.glade
  synfig-studio/src/gui/resources/ui/synfig-catalog.xml
  synfig-studio/src/gui/widgets/widget_link.cpp
  synfig-studio/src/gui/widgets/widget_link.h
Labels: GUI

#2988 fix: crash occurs under Wayland when using tablet
  synfig-studio/src/gui/canvasview.cpp
  synfig-studio/src/gui/workarea.cpp
  synfig-studio/src/synfigapp/main.cpp
Labels: Crash, Backport

#2991 fix: drawing tablet didn't work on Wayland
  synfig-studio/src/gui/workarea.cpp
Labels: Backport
