Repository synfig/synfig, pull requests merged in 2023-09, with the labels that each got.

#3207 fix: selecting a handle while the Graphs window tooltip is open crashes the gui
  synfig-studio/src/gui/widgets/widget_curves.cpp
Labels: Crash

#3223 fix: fixed macOS Info.plist file
  autobuild/osx/app-template/Contents/Info.plist
Labels: macOS

#3220 fix(Windows): plugins fail to run for files with non-latin characters
  synfig-core/po/POTFILES.in
  synfig-core/src/synfig/filesystemtemporary.cpp
  synfig-core/src/synfig/filesystemtemporary.h
  synfig-studio/src/gui/app.cpp
  synfig-studio/src/gui/instance.cpp
Labels: Windows
