Repository synfig/synfig, pull requests merged in 2025-04, with the labels that each got.

#3534 fix: couldn't create converter to spline tangent or spline width (regression)
  synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
  synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp
Labels: Regression

#3512 fix(audio): add length check for MLT track loading
  synfig-studio/src/gui/widgets/widget_soundwave.cpp
Labels: Crash

#3561 fix(ui): rectify wayland window icon
  synfig-studio/src/gui/main.cpp
Labels: Linux
